# Generated by Django 2.0 on 2017-12-28 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='client_uuid',
            field=models.UUIDField(default=None),
        ),
    ]
