# Generated by Django 2.0 on 2017-12-28 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0002_eventmodel_client_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='client_uuid',
            field=models.UUIDField(),
        ),
    ]
