# Generated by Django 2.0 on 2017-12-30 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0004_eventmodel_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
